#+title: arch-setup
#+author: Mathias Estrup

Post installation script for Arch Linux. This script installs all of the
software that I like to use and configures it to my liking.

* Prerequisites
There are three prerequisites to running this scripts:
1. You must have installed Arch Linux already. See the [[https://wiki.archlinux.org/title/Installation_guide][Arch Installation Guide]].
2. You must have installed appropriate graphics drivers for Xorg to run. See the wiki [[https://wiki.archlinux.org/title/Xorg#Driver_installation][article]] about Xorg driver installation.
3. You must have set up a user with sudo privileges. See [[https://wiki.archlinux.org/title/Users_and_groups][Users and groups]] and [[https://wiki.archlinux.org/title/Sudo][Sudo]] for instructions - I recommend assigning your user to the /wheel/ group and configuring =sudo= to let all /wheel/ group members use it.

You do not need to have set anything else up such as a graphical environment, although you will need a working internet connection and [[https://git-scm.com][git]], which can be installed with:

#+begin_src bash
sudo pacman -S git
#+end_src

* Installation
Simply clone the repository and run the script:

#+begin_src sh
git clone https://github.com/mestru17/arch-setup.git
cd arch-setup
./arch-setup
#+end_src

*NOTE:* It is important that you =cd= into the =arch-setup= directory
before running the script (as in the instructions above) as it needs
access to the other files in the directory and expects the working
directory to be there. Running the script from another directory may
have unknown consequences.
